const keys = Object.keys(process.env);
const interesting = keys.filter(k => /RENDER|VERCEL|KAGGLE|COLAB|GOOGLE|NEXT_PUBLIC|SUPABASE|WORKER|CRON|DATABASE|API_URL/i.test(k));
console.log("INTERESTING_KEYS", interesting.sort().join(", "));
console.log("ALL_KEYS_COUNT", keys.length);
console.log("HAS_KAGGLE_API_TOKEN", !!process.env.KAGGLE_API_TOKEN);
console.log("HAS_KAGGLE_KERNEL_REF", !!process.env.KAGGLE_KERNEL_REF, process.env.KAGGLE_KERNEL_REF ? process.env.KAGGLE_KERNEL_REF.slice(0,40) : "empty");
console.log("HAS_NEXT_PUBLIC_API_URL", !!process.env.NEXT_PUBLIC_API_URL, process.env.NEXT_PUBLIC_API_URL ? process.env.NEXT_PUBLIC_API_URL.slice(0,60) : "empty");
console.log("HAS_SUPABASE_URL", !!process.env.SUPABASE_URL);
console.log("HAS_SUPABASE_CONNECTION_STRING", !!process.env.SUPABASE_CONNECTION_STRING);
console.log("HAS_WORKER_REGISTRATION", !!(process.env.WORKER_REGISTRATION_TOKEN || process.env.WORKER_REGISTRATION_SECRET));
console.log("NODE_ENV", process.env.NODE_ENV);
